# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6485809a8e392d3bf6a344f1fa9ea65a59d463487b22e117a71333e99eabe18a49fc9aa8e1aee23774afe5fab420afd11a43a5a1b91e13b540132eed30e07dd

test:
  secret_key_base: 86722443764ff3c4d3a7fec7e400c94be5d3eae88715b1a299c79a7eb8aaf9dc1e5b317eca04f6f5f6ff9a5ce58d1557c7dd91bbbab502d5daa900fbc0ed5fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
